/* tslint:disable */
/* eslint-disable */
/**
 * Arc Pipeline API
 * HTTP API for managing Arc pipeline executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiQuestionOption } from './api-question-option';

export interface ApiQuestion {
    'id': string;
    'text': string;
    'question_type': string;
    'options': Array<ApiQuestionOption>;
    'allow_freeform': boolean;
}

