/* tslint:disable */
/* eslint-disable */
/**
 * Arc Pipeline API
 * HTTP API for managing Arc pipeline executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const PipelineStatus = {
    RUNNING: 'running',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled'
} as const;

export type PipelineStatus = typeof PipelineStatus[keyof typeof PipelineStatus];



