/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LlmConfiguration } from './llm-configuration';

/**
 * Optional request body for starting a workflow run with overrides.
 */
export interface StartWorkflowRunRequest {
    /**
     * Goal description override for this run.
     */
    'goal'?: string;
    /**
     * Variable map overrides for template expansion.
     */
    'vars'?: { [key: string]: string; };
    'llm'?: LlmConfiguration;
}

